### ISSUE TITLE
Question: confusion regarding the 'note taking' example

### ISSUE THREAD

**Issue by x3ro** [gamburg/margin#20]
When looking at the note taking example on the [Try margin](https://margin.love/parser/) page, the first couple of lines of content currently look like this (SublimeText screenshot so that invisible characters are visible):

![Screenshot 2020-05-19 at 15 09 05](https://user-images.githubusercontent.com/243719/82330409-178d8d00-99e3-11ea-8250-3395de6f4a51.png)

I'm somewhat confused about the resulting AST, so here are my questions:

* Is the single space character after the tabs before "course notes" intentional? It causes the subsequent lines to not be children of the "course notes" line, which seems accidental (?)
* If I remove a single tab from the `Graphic design [...]` line it becomes a child of the previous line, though in that case I would expect it not to be, given that both lines now share the same level of indentation? ![Screenshot 2020-05-19 at 15 14 43](https://user-images.githubusercontent.com/243719/82330726-7eab4180-99e3-11ea-9b52-c0964c937667.png)

This is potentially related to #5, since it appears to be caused by mixing of tabs and spaces 🤔

**Comment by gamburg** [comment]
Good catch on both! The single space was indeed a mistake.

As for the issue with the indentation levels, that incorrect behavior is likely due to the incompleteness of the js parser (there are many things in the js parser that are not to spec). 

I'm hoping to dive into #4 (and some open questions around the spec) before worrying too much about getting the example parser up to spec.
